### ISSUE TITLE
Add a XCode Shortcut

### ISSUE THREAD

**Issue by juliengdt** [bsarrazin/soothe#2]
All is in the title: 

Is it possible to add a customizable shortcut for aligning selected stuff❓ 

Julien

**Comment by bsrz** [comment]
@juliengdt I haven't looked into making command automatically map to Xcode shortcuts, however, you can manually do so in Xcode's preferences. I have done these:

![2017-01-27 at 8 35 am](https://cloud.githubusercontent.com/assets/1077441/22372633/d34348cc-e46b-11e6-8406-b38d895b1ebf.png)

**Comment by juliengdt** [comment]
Oh great ! thanks
